package lt.vu.mybatis.model;

public class Arena {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARENA.ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARENA.ADDRESS
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARENA.CAPACITY
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private Long capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARENA.NAME
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARENA.HOMETEAM_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private Integer hometeamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARENA.ID
     *
     * @return the value of PUBLIC.ARENA.ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARENA.ID
     *
     * @param id the value for PUBLIC.ARENA.ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARENA.ADDRESS
     *
     * @return the value of PUBLIC.ARENA.ADDRESS
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARENA.ADDRESS
     *
     * @param address the value for PUBLIC.ARENA.ADDRESS
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARENA.CAPACITY
     *
     * @return the value of PUBLIC.ARENA.CAPACITY
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public Long getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARENA.CAPACITY
     *
     * @param capacity the value for PUBLIC.ARENA.CAPACITY
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARENA.NAME
     *
     * @return the value of PUBLIC.ARENA.NAME
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARENA.NAME
     *
     * @param name the value for PUBLIC.ARENA.NAME
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARENA.HOMETEAM_ID
     *
     * @return the value of PUBLIC.ARENA.HOMETEAM_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public Integer getHometeamId() {
        return hometeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARENA.HOMETEAM_ID
     *
     * @param hometeamId the value for PUBLIC.ARENA.HOMETEAM_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setHometeamId(Integer hometeamId) {
        this.hometeamId = hometeamId;
    }
}