package lt.vu.mybatis.model;

public class TeamLeague {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_LEAGUE.TEAMS_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private Integer teamsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_LEAGUE.LEAGUES_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    private Long leaguesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_LEAGUE.TEAMS_ID
     *
     * @return the value of PUBLIC.TEAM_LEAGUE.TEAMS_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public Integer getTeamsId() {
        return teamsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_LEAGUE.TEAMS_ID
     *
     * @param teamsId the value for PUBLIC.TEAM_LEAGUE.TEAMS_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setTeamsId(Integer teamsId) {
        this.teamsId = teamsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_LEAGUE.LEAGUES_ID
     *
     * @return the value of PUBLIC.TEAM_LEAGUE.LEAGUES_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public Long getLeaguesId() {
        return leaguesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_LEAGUE.LEAGUES_ID
     *
     * @param leaguesId the value for PUBLIC.TEAM_LEAGUE.LEAGUES_ID
     *
     * @mbg.generated Tue Mar 26 21:26:35 EET 2024
     */
    public void setLeaguesId(Long leaguesId) {
        this.leaguesId = leaguesId;
    }
}